### ISSUE TITLE
Forward references

### ISSUE THREAD

**Issue by Vineg** [aparapi/aparapi#22]
There is forward references when there is no more new methods to discover, yet call tree is not completely analyzed. I fixed it here https://github.com/Vineg/aparapi/commit/4386305bd5d93ca95146018d3106a46918b5b009 but since patch appeared to be quite ugly, I didn't create pull request.

**Comment by Ryan-LaMothe-PNNL** [comment]
What needs to happen to clean-up pull request?

Sent from my iPhone --- Please excuse any typos or autocorrect mistakes

On Jan 7, 2016, at 8:13 AM, George Vinokhodov <notifications@github.com<mailto:notifications@github.com>> wrote:


There is forward references when there is no more new methods to discover, yet call tree is not completely analyzed. I fixed it here Vineg/aparapi@4386305<https://github.com/Vineg/aparapi/commit/4386305bd5d93ca95146018d3106a46918b5b009> but since patch appeared to be quite ugly, I didn't create pull request.

**Comment by Vineg** [comment]
It is pretty difficult question in general, since most mess comes from formatting differences. In this particular case I could probably rewrite patch without autoformatting.

**Comment by grfrost** [comment]
Yes i took a look at the patch and noticed that most of the changes were
formatting.

It would be great to have a patch without the formatting 'noise'

Gary

On Thu, Jan 7, 2016 at 10:59 AM, George Vinokhodov <notifications@github.com

**Comment by freemo** [comment]
This issue was moved to Syncleus/aparapi#8

**Comment by rlamothe** [comment]
I am working on adding this patch manually right now...will take a little while. Just out of curiosity, why did @grfrost make the following code comment?

`if (methodMap.keySet().contains(m)) {
-                     // we remove and then add again.  Because this is a LinkedHashMap this 
-                     // places this at the end of the list underlying the map
-                     // then when we reverse the collection (below) we get the method 
-                     // declarations in the correct order.  We are trying to avoid creating forward references`

**Comment by rlamothe** [comment]
Hand merged your patch to Trunk. Thank you!!!
