### ISSUE TITLE
user supplied Device incompatible with current EXECUTION_MODE

### ISSUE THREAD

**Issue by zijiecong** [aparapi/aparapi#26]
It seems that Kernel.setExecutionMode() is deprecated. But when no EXECUTION_MODE is specified (or set to AUTO), my code throws:

> Exception in thread "main" java.lang.AssertionError: user supplied Device incompatible with current EXECUTION_MODE or getTargetDevice(); device = AMD<GPU>; kernel = MatrixKernel, devices={Intel<GPU>|AMD<GPU>|Intel<CPU>|AMD<CPU>|Java Alternative Algorithm|Java Thread Pool}
	at com.amd.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1206)

` public static long runTest(Device device, final int r) {

        Range range = device.createRange(r * r);
        double[] randomMatrixA = getRandomSquareMatrix(r);
        double[] randomMatrixB = getRandomSquareMatrix(r);
        MatrixKernel matrixKernel = new MatrixKernel(randomMatrixA, randomMatrixB, r);

        matrixKernel.setExecutionMode(Kernel.EXECUTION_MODE.AUTO);

        final long time1 = System.currentTimeMillis();
        matrixKernel.execute(range);
        return (System.currentTimeMillis() - time1);
    }`

**Comment by jytou** [comment]
Just in case anyone else comes across this: the workaround I've found is to set the preferred devices in the KernelManager (you can list all GPU devices from OpenCLDevice.listDevices(TYPE.GPU)):

>KernelManager.instance().setDefaultPreferredDevices(new LinkedHashSet<>(Arrays.asList(new Device[] {your_device_here)})));

And from there the next kernel execution runs on that device. The problem is that a Kernel is automatically attached to a device but there doesn't seem to be a way to change that device, else than going through the KernelManager. If anyone else has a better idea, I'd love to hear from them.
